Fix automatic conversions of function/method args for java interfaces…
jython/jython pull request #296
Opened 2023-12-31 17:27 UTC by pturmel

… with default methods.

Java 8's default methods in interfaces breaks jython's assumptions about lambda-qualified interfaces.  Specifically, jython checks for a single method (or single-named collection of methods) in an interface, but does not exclude interface default methods.

Correct both the decision to supply a proxy in __tojava__() and invocation of the proxy in invoke(), in both PyFunction.java and PyMethod.java.

2023-12-31 17:28 UTC, pturmel commented
Prior discussion on #278.

Test case to follow.

2023-12-31 23:10 UTC, pturmel commented
Test cases complete.

2023-12-31 23:14 UTC, pturmel commented
I couldn't help but notice that the Callable coercion test is disabled.  I investigated, because I thought I'd add a test case for Callable conversion to Consumer, too. (Did not work, of course.)  I suspect the balance of that old issue could be solved with similar proxy code in `PyInstance`.

(I did not find that old issue in the github list.  Should it be resurrected for a possible complete fix?)

2024-01-01 19:40 UTC, jeff5 commented
> (I did not find that old issue in the github list. Should it be resurrected for a possible complete fix?)

I looked at that too. It sounds like Jim had an idea but it wasn't as simple as he thought. If you think you have an answer feel free to replicate the issue on GH. Unlike CPython, we have not replicated open BJO issues mechanically, and anyway, I'd appreciated it explained more carefully than Jim has there.

The idea seems to be that an object with `__call__` should automatically be a Java `Callable`. However, note that `PyInstance` is only for [classic (old-style) classes](https://docs.python.org/2.7/reference/datamodel.html#new-style-and-classic-classes).

Separate PR if you think you have a  fix.

2024-01-01 20:33 UTC, pturmel commented
> only for [classic (old-style) classes](https://docs.python.org/2.7/reference/datamodel.html#new-style-and-classic-classes).

Ew.  Ok, not so simple.  I'll poke at it later.

2024-01-08 20:55 UTC, jeff5 requested changes
This looks good to me. I took the time to single-step through a lot of it, most of which you haven't changed, because it's quite intense stuff and I wouldn't say my grasp of it was perfect. It was more a question of feeling comfortable this is the behaviour we want, rather than questioning whether it is done right. The tests, though simple, helped a lot thanks.

There are minor formatting problems in the new material, but that's all.

Also, would you please:

- [ ] Merge from `master` into your PR branch.
- [ ] Add a line to NEWS like `[ GH-277 ] ...` 
- [ ] Add yourself to ACKNOWLEGMENTS.
- [ ] Run the regression tests again.
- [ ] Commit and push.

Thanks for doing this.

2024-01-08 20:55 UTC, jeff5 commented on Lib/test/test_java_integration.py
Two lines around top-level functions and classes.

2024-01-08 20:55 UTC, jeff5 commented on src/org/python/core/PyFunction.java
> +                        if (method.isDefault())
We have braces around all bodies (in any code less than about 15 years old). For ease of reading, I would do this as:
```
if (...) {
    continue;
} else if (...) {
    ...
} else {
    ...
}
```

2024-01-08 20:55 UTC, jeff5 commented on src/org/python/core/PyMethod.java
> +                        if (method.isDefault())
And the same `if (...) { ... } else if (...)` here.

2024-01-14 20:50 UTC, pturmel commented
Done, but with a slight tweak.

I added the braces around `continue;` as requested, but omitted the following `else`.  With it, IntelliJ flagged the `continue` as unnecessary, but it really is necessary. Any code added in the future after the next `if` would be accidentally run if a code cleanup deleted the `continue` as IntelliJ was recommending.

2024-01-15 08:50 UTC, jeff5 approved these changes

2024-01-15 09:00 UTC, jeff5 commented
I see where IntelliJ is coming from. Since there is no code after the if-nest, the body could be empty. However, that would look odd. What you have is fine (conformant).

My personal preference is for if statements to leave by the bottom (maybe `return` in simple code), so I'm not fond of `continue`. Here it would would probably be `// pass`.

2024-01-16 11:44 UTC, merged

2024-01-16 11:48 UTC, jeff5 commented
Thanks for this @pturmel, it was an education to review it.

2024-01-16 15:00 UTC, pturmel commented
Heh. Jython has been cracking my skull for 15 years or so, thanks to a particular commercial user of jython with whom I'm heavily involved.  (Immediately obvious if you google me.)